// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-courses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function getClient() {
  const env = globalThis.process?.env ?? {};
  const url = env.SUPABASE_URL;
  const key = env.SUPABASE_PUBLISHABLE_KEY ?? env.SUPABASE_ANON_KEY;
  if (!url || !key) {
    throw new Error("Backend environment is not configured for MCP tools.");
  }
  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_courses_default = defineTool({
  name: "list_courses",
  title: "List courses",
  description: "Returns active courses published on the academy website.",
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async () => {
    const supabase = getClient();
    const { data, error } = await supabase.from("courses").select("name, slug, duration, description").eq("active", true).order("display_order");
    if (error) {
      return {
        content: [{ type: "text", text: `Failed to load courses: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(data ?? [], null, 2)
        }
      ],
      structuredContent: { courses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-latest-blog-posts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.89.0";
function getClient2() {
  const env = globalThis.process?.env ?? {};
  const url = env.SUPABASE_URL;
  const key = env.SUPABASE_PUBLISHABLE_KEY ?? env.SUPABASE_ANON_KEY;
  if (!url || !key) {
    throw new Error("Backend environment is not configured for MCP tools.");
  }
  return createClient2(url, key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_latest_blog_posts_default = defineTool2({
  name: "list_latest_blog_posts",
  title: "List latest blog posts",
  description: "Returns the latest published blog posts from the website.",
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async () => {
    const supabase = getClient2();
    const { data, error } = await supabase.from("blog_posts").select("title, slug, excerpt, created_at").eq("published", true).order("created_at", { ascending: false }).limit(10);
    if (error) {
      return {
        content: [{ type: "text", text: `Failed to load blog posts: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(data ?? [], null, 2)
        }
      ],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-site-settings.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.89.0";
function getClient3() {
  const env = globalThis.process?.env ?? {};
  const url = env.SUPABASE_URL;
  const key = env.SUPABASE_PUBLISHABLE_KEY ?? env.SUPABASE_ANON_KEY;
  if (!url || !key) {
    throw new Error("Backend environment is not configured for MCP tools.");
  }
  return createClient3(url, key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_site_settings_default = defineTool3({
  name: "get_site_settings",
  title: "Get site settings",
  description: "Returns the current public contact and branding settings.",
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: async () => {
    const supabase = getClient3();
    const { data, error } = await supabase.from("site_settings").select("site_name, tagline, email, phone, address, office_hours").limit(1).maybeSingle();
    if (error) {
      return {
        content: [{ type: "text", text: `Failed to load site settings: ${error.message}` }],
        isError: true
      };
    }
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(data ?? {}, null, 2)
        }
      ],
      structuredContent: { settings: data ?? {} }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "winacademy-mcp",
  title: "Win Academy MCP",
  version: "0.1.0",
  instructions: "Use these tools to read Win Academy public content and settings when answering content and website questions.",
  tools: [list_courses_default, list_latest_blog_posts_default, get_site_settings_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
